---
output: 
  pdf_document:
    keep_tex: true
    fig_caption: yes
    latex_engine: pdflatex
    template: /Volumes/GoogleDrive/My Drive/Teaching/STAT534/STAT534_2019/template.tex
geometry: margin=1in

title: "STAT 506: Advanced Regression Analysis"
author: Andrew Hoegh
date: "Spring 2021"

email: "andrew.hoegh@montana.edu"
web: "stat506.github.io"
officehours: "TBD"
office: "Wilson Hall 2-241"
classroom: "*Wilson Hall 1-144*"
classhours: "MWF 10:00-10:50"

fontfamily: mathpazo
fontsize: 11pt
header-includes:
   - \linespread{1.05}
---



```{r setup, include=FALSE}
knitr::opts_chunk$set(cache=FALSE, dev='pdf')
monday <- as.Date("2019-08-26")
#tues <- as.Date("2019-01-15")

advdate <- function(obj, adv) {
 tmon <- obj + 7*(adv-1)
 tfri <- obj + 4 + 7*(adv-1)
 tmon <- format(tmon, format="%m/%d")
 tfri <- format(tfri, format="%m/%d")
 zadv <- sprintf("%02d", adv)
 tmp <- paste("Week ",zadv,sep='',", ", tmon," - ",tfri)
 return(tmp)
}

#library(RefManageR)
#library(knitcitations)
# library(rcrossref)
#bib <- ReadBib("~/Dropbox/master.bib")
#myopts <- BibOptions(bib.style = "authoryear", style="latex", first.inits=FALSE, max.names = 20)

```

# Course Description

This course will continue wrap up linear models and generalized linear models from STAT505, including a more detailed look at the underlying linear algebra. In addition, the course will present advanced regression techniques including hierarchical models.

# Learning Outcomes:

- To fit hierarchical models in R and SAS and interpret the results.
- To fit models which take into account common forms of correlation.
- To fit models which take into account common forms of non-constant variance.
- To make inference using models which do not assume normality of residuals.
- To fit Bayesian models using Markov Chain Monte Carlo algorithms and to interpret results.

# Additional Topics

- Understand the derivation of generalized least squares estimates.
- To know when the Gauss-Markov theorem applies and what it provides.
- To interpret results from Poisson and logistic regression models.
- To understand when causal inference can be made from observational studies.


# Prerequisites

- Required: STAT 505

# Textbooks

- _Regression and Other Stories_, by Andrew Gelman, Jennifer Hill, and Aki Vehtari 
- \emph{Data Analysis Using Regression and Multilevel/Hierarchical Models}, by Andrew Gelman and Jennifer Hill

# Additional Resources
Analysis, data visualization, and version control procedures will be implemented with:

- R / R Studio
- Git / Github

For additional resources see:

- R for Data Science, [https://r4ds.had.co.nz](https://r4ds.had.co.nz)
- Happy Git and GitHub for the useR,  [https://happygitwithr.com](https://happygitwithr.com)

# Course Policies


### Grading Policy

- **30%** of your grade will be determined by weekly homework assignments. Students are allowed and encouraged to work with classmates on homework assignments, but each student is required to complete their own homework. 

- **30%** of your grade will be determined by a final exam.

- **40%** of your grade will be determined by a series of projects. The projects will be due roughly every 3 - 4 weeks during the course of the semester and may require oral presentations.


### Collaboration
University policy states that, unless otherwise specified, students may not collaborate on graded material. Any exceptions to this policy will be stated explicitly for individual assignments. If you have any questions about the limits of collaboration, you are expected to ask for clarification.

In this class students are encouraged to collaborate on homework assignments, but exams and projects should be completed without collaboration.

###  Academic Misconduct
Section 420 of the Student Conduct Code describes academic misconduct as including but not limited to plagiarism, cheating, multiple submissions, or facilitating others’ misconduct. Possible sanctions for academic misconduct range from an oral reprimand to expulsion from the university.

### Disabilities Policy

Federal law mandates the provision of services at the university-level to qualified students with disabilities. If you have a documented disability for which you are or may be requesting an accommodation(s), you are encouraged to contact the Office of Disability Services as soon as possible.

### Masks

WEARING MASKS IN CLASSROOMS IS REQUIRED Face coverings that cover the mouth and nose are required in all indoor spaces and all enclosed or partially enclosed outdoor spaces. MSU requires all students to wear face masks or cloth face coverings in classrooms, laboratories and other similar spaces where in-person instruction occurs. MSU requires the wearing of masks in physical classrooms to help mitigate the transmission of SARS-CoV-2, which causes COVID-19. The MSU community views the adoption of these practices as a mark of good citizenship and respectful care of fellow classmates, faculty, and staff.

The complete details about MSU’s mask requirement can be found at https://www.montana.edu/health/coronavirus/index.html.

These requirements from the Office of the Commissioner of Higher Education are detailed in the MUS Healthy Fall 2020 Guidelines, Appendix B.

For more information: https://www.montana.edu/health/coronavirus/prevention/index.html

Compliance with the face-covering protocol is expected. If a you do not comply with a classroom rule, you may be requested to leave class. Section 460.00 of the MSU Code of Student Conduct covers “disruptive student behavior.”

### Health-Related Class Absences

Please evaluate your own health status regularly and refrain from attending class and other on-campus events if you are ill. MSU students who miss class due to illness will be given opportunities to access course materials online. You are encouraged to seek appropriate medical attention for treatment of illness. In the event of contagious illness, please do not come to class or to campus to turn in work. Instead notify me by email about your absence as soon as practical, so that accommodations can be made. Please note that documentation (a Doctor’s note) for medical excuses is not required. MSU University Health Partners - as part their commitment to maintain patient confidentiality, to encourage more appropriate use of healthcare resources, and to support meaningful dialogue between instructors and students - does not provide such documentation.

### Course Communication

In the event that one or more students and/or the instructor are required to quarantine or if the university moves courses online, the course may need to continue in a virtual format. Communication about how the course will proceed will be available through D2l.

### Virtual Attendance

Due to the ongoing pandemic and issues stemming from this, a synchronous virtual attendance option will be permitted for this course. The Microsoft Teams platform will be used for this virtual option. When attending virtually, if at all possible, please plan to have your video camera turned on.

# Approximate Course Outline

1. LM Recap + GLM Review
2. Linear Algebra Section
3. Design and Sample Size Decisions
4. Advanced Regression Overview
5. Hierarchical Models
6. Causal Inference

